Traceback (most recent call last):
  File "/home/miha/work/orange/testing/regressionTests/xtest_one.py", line 97, in <module>
    execfile(t__name)
  File "serverfiles2.py", line 13, in <module>
    authenticated.create_domain('demo2')
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 246, in create_domain
    return self._open('createdomain', { 'domain': domain })
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 429, in _open
    return self._handle(command, data).read()
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 426, in _handle
    return self._server_request(addr, command, data)
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 419, in _server_request
    return self._server_request(root, command, data, repeat=repeat-1)
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 419, in _server_request
    return self._server_request(root, command, data, repeat=repeat-1)
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 414, in _server_request
    return do()
  File "/home/miha/work/orange/orange/Orange/misc/serverfiles.py", line 411, in do
    return opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
